import type { Metadata } from "next";
import { Encode_Sans } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import { Navbar } from "./_Component/Navbar/Navbar";
import Footer from "./_Component/Footer/Footer";
import { Toaster } from "@/components/ui/sonner";
import UserProvider from "./UserProvider";
import CouontProvider from "@/CountProvider";

const Encode_SansFont = Encode_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Encode_SansFont.className}`}>
        <UserProvider>
          <CouontProvider>
            <Navbar />
            <main className="p-5">{children}</main>
            <Toaster />
            <Footer />
          </CouontProvider>
        </UserProvider>
      </body>
    </html>
  );
}
